# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

env:
    next_mode: preminor
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_prerelease:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - id: compute_tag
      uses: markjackmilian/compute-tag@master
      with:
        github_token: ${{ github.token }}
        #version_type: preminor 
    
    
    - name: SetPrerelease or PreMinor
      run: |
        if [[ ${{ steps.compute_tag.outputs.previous_tag }} == *"beta"* ]]; then
        echo set to prerelease
        echo ::set-env name=next_mode::prerelease
        fi
        
    - name: Show Var
      run: echo ${{ env.next_mode }}
    
    - id: compute_tag2
      uses: markjackmilian/compute-tag@master
      with:
        github_token: ${{ github.token }}
        version_type: ${{ env.next_mode }} 
    
    - name: create release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.compute_tag2.outputs.next_tag }}
        release_name: ${{ steps.compute_tag2.outputs.next_tag }}
        prerelease: true
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
